export const recommendations = [
  {
    title: 'This Will Be The Title Of The Book',
    author: 'Author Name',
    avatar: '/images/books4dev/twitterAvatar.jpg',
    description: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque temporibus hic soluta voluptatibus consectetur, quo aspernatur. Veniam atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque temporibus hic soluta voluptatibus consectetur, quo aspernatur. Veniam atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt.'
    ],
    guest: 'Michael Gee',
    guestUrl: 'https://michaelgee.com'
  },
  {
    title: 'This Will Be The Title Of The Book',
    author: 'Author Name',
    avatar: '/images/books4dev/twitterAvatar.jpg',
    description: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque temporibus hic soluta voluptatibus consectetur, quo aspernatur. Veniam atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque temporibus hic soluta voluptatibus consectetur, quo aspernatur. Veniam atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt.'
    ],
    guest: 'Michael Gee',
    guestUrl: 'https://michaelgee.com'
  },
  {
    title: 'This Will Be The Title Of The Book',
    author: 'Author Name',
    avatar: '/images/books4dev/twitterAvatar.jpg',
    description: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque temporibus hic soluta voluptatibus consectetur, quo aspernatur. Veniam atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque temporibus hic soluta voluptatibus consectetur, quo aspernatur. Veniam atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt.'
    ],
    guest: 'Michael Gee',
    guestUrl: 'https://michaelgee.com'
  },
  {
    title: 'This Will Be The Title Of The Book',
    author: 'Author Name',
    avatar: '/images/books4dev/twitterAvatar.jpg',
    description: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque temporibus hic soluta voluptatibus consectetur, quo aspernatur. Veniam atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab pariatur quibusdam ipsa dolorum atque temporibus hic soluta voluptatibus consectetur, quo aspernatur. Veniam atque doloribus saepe molestiae ducimus a at quia. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius perspiciatis nihil labore pariatur, inventore neque illo, nobis quod nulla autem quaerat? Totam illo expedita repudiandae, vero quibusdam perspiciatis adipisci aliquid. Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ipsam libero dolores fugit impedit laudantium odit autem facilis ducimus delectus iure provident dicta nam voluptatum voluptates expedita, veniam corruptinesciunt.'
    ],
    guest: 'Michael Gee',
    guestUrl: 'https://michaelgee.com'
  }
]
