service:
  name: michaelgee-dev-server

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

custom:
  bundle:
    linting: false

functions:
  hello:
    handler: src/handlers/handler.hello
    description: Initial test handler with serverless framework
    events:
      - http:
          method: get
          path: hello
